// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"gf-in-action/app/model/internal"
)

// Id is the golang structure for table id.
type Id internal.Id

// Fill with you ideas below.
