// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// Id is the golang structure for table id.
type Id struct {
	Id int `orm:"id,primary" json:"id"` //
}
