// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        uint        `orm:"id,primary" json:"id"`         //
	Username  string      `orm:"username"   json:"username"`   //
	Email     string      `orm:"email"      json:"email"`      //
	Password  string      `orm:"password"   json:"password"`   //
	Passsalt  string      `orm:"passsalt"   json:"passsalt"`   //
	Deleted   int         `orm:"deleted"    json:"deleted"`    //
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"` //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"` //
}
