# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	# LogPath     = "/tmp/log/gf-app/server"
    LogPath     = "C:\\dev\\go\\gf-demo\\runtime"

# Logger.
[logger]
    Path        = "C:\\dev\\go\\gf-demo\\runtime"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/gf-in-action"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "C:\\dev\\go\\gf-demo\\runtime\\sql"
        Level  = "all"
        Stdout = true