// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gf-in-action/app/dao/internal"
)

// idDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type idDao struct {
	*internal.IdDao
}

var (
	// Id is globally public accessible object for table id operations.
	Id = &idDao{
		internal.Id,
	}
)

// Fill with you ideas below.
